"""Property tests for SMACalculator.

This module contains property-based tests for the SMACalculator class,
verifying universal properties across many randomly generated inputs.
"""

from typing import List
import math

from hypothesis import given, settings, strategies as st
import pytest

from spy_sma_alert_bot.services.sma_calculator import SMACalculator

# Feature: spy-sma-alert-bot, Property 6: SMA calculation correctness
@settings(max_examples=100, deadline=None)
@given(
    prices=st.lists(st.floats(min_value=0.01, max_value=1000.0), min_size=0, max_size=200),
    period=st.integers(min_value=1, max_value=100)
)
def test_sma_calculation_correctness(prices: List[float], period: int) -> None:
    """Property test for SMA calculation correctness.

    For any sequence of closing prices and any SMA period N, the calculated SMA should
    equal the arithmetic mean of the last N closing prices.

    Args:
        prices: List of closing prices (generated by Hypothesis)
        period: SMA period (generated by Hypothesis)

    Validates: Requirement 3.1
    """
    # Calculate SMA using the SMACalculator
    calculated_sma = SMACalculator.calculate_sma(prices, period)

    # Handle edge cases
    if not prices or len(prices) < period:
        # Insufficient data - should return None
        assert calculated_sma is None, f"Expected None for insufficient data, got {calculated_sma}"
    else:
        # Sufficient data - should return arithmetic mean
        window = prices[-period:]
        expected_sma = sum(window) / period

        # Handle floating point precision
        assert calculated_sma is not None
        assert math.isclose(calculated_sma, expected_sma, rel_tol=1e-9), (
            f"SMA calculation incorrect: expected {expected_sma}, got {calculated_sma}. "
            f"Prices: {prices}, period: {period}, window: {window}"
        )

def test_sma_calculation_edge_cases() -> None:
    """Test edge cases for SMA calculation."""
    # Test with empty list
    assert SMACalculator.calculate_sma([], 10) is None

    # Test with insufficient data
    assert SMACalculator.calculate_sma([1.0, 2.0, 3.0], 5) is None

    # Test with exact period match
    assert math.isclose(SMACalculator.calculate_sma([1.0, 2.0, 3.0, 4.0], 4), 2.5)

    # Test with single price and period 1
    assert math.isclose(SMACalculator.calculate_sma([42.0], 1), 42.0)

    # Test with invalid period (should raise ValueError)
    with pytest.raises(ValueError):
        SMACalculator.calculate_sma([1.0, 2.0, 3.0], 0)

    with pytest.raises(ValueError):
        SMACalculator.calculate_sma([1.0, 2.0, 3.0], -5)

def test_calculate_all_smas() -> None:
    """Test the calculate_all_smas method."""
    # Test with empty list
    result = SMACalculator.calculate_all_smas([])
    assert result == {25: None, 50: None, 75: None, 100: None}

    # Test with insufficient data for all periods
    result = SMACalculator.calculate_all_smas([1.0, 2.0, 3.0])
    assert result == {25: None, 50: None, 75: None, 100: None}

    # Test with sufficient data for some periods
    prices = list(range(1, 61))  # 1 to 60
    result = SMACalculator.calculate_all_smas(prices)

    # Should have values for 25 and 50, but None for 75 and 100
    assert result[25] is not None
    assert result[50] is not None
    assert result[75] is None
    assert result[100] is None

    # Verify the 25-day SMA calculation
    expected_25 = sum(range(36, 61)) / 25  # Last 25 prices: 36 to 60
    assert math.isclose(result[25], expected_25, rel_tol=1e-9)